#!/usr/bin/env node
/**
 * Injects system prompt into worker at build time
 * Reads from: ../system-prompt.md, ../content/system-prompt.md, or
 *             SYSTEM_PROMPT env var (CI). Emits an empty stub if none
 *             of those exist so the worker still compiles.
 * Writes to: src/system-prompt.ts
 */

const fs = require('fs');
const path = require('path');

const outputPath = path.join(__dirname, '../src/system-prompt.ts');
// content/ wins over the template-fork root so split-repo users keep a
// single source of truth for their prompt. SYSTEM_PROMPT env still overrides.
const promptPaths = [
  path.join(__dirname, '../../content/system-prompt.md'),
  path.join(__dirname, '../../system-prompt.md'),
];

let prompt = '';

// Resolution order: env var (CI) → content/system-prompt.md → root system-prompt.md
if (process.env.SYSTEM_PROMPT) {
  console.log('Using SYSTEM_PROMPT from environment');
  prompt = process.env.SYSTEM_PROMPT;
} else {
  let loaded = false;
  for (const p of promptPaths) {
    if (fs.existsSync(p)) {
      console.log(`Using system prompt from ${path.relative(path.join(__dirname, '../..'), p)}`);
      prompt = fs.readFileSync(p, 'utf-8');
      loaded = true;
      break;
    }
  }
  if (!loaded) {
    console.warn('No system prompt found — emitting empty stub.');
    console.warn('Set SYSTEM_PROMPT env var or create system-prompt.md (root or content/) to customize.');
  }
}

// Escape backticks and ${} for template literal
const escaped = prompt
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${');

const output = `// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/inject-prompt.js at build time

export const SYSTEM_PROMPT = \`${escaped}\`;
`;

fs.writeFileSync(outputPath, output);
console.log('Generated src/system-prompt.ts');
