#!/usr/bin/env node
/**
 * Injects system prompt into worker at build time
 * Reads from: ../system-prompt.md (local) or SYSTEM_PROMPT env var (CI)
 * Writes to: src/system-prompt.ts
 */

const fs = require('fs');
const path = require('path');

const outputPath = path.join(__dirname, '../src/system-prompt.ts');
const localPromptPath = path.join(__dirname, '../../system-prompt.md');

let prompt;

// Try environment variable first (CI), then local file
if (process.env.SYSTEM_PROMPT) {
  console.log('Using SYSTEM_PROMPT from environment');
  prompt = process.env.SYSTEM_PROMPT;
} else if (fs.existsSync(localPromptPath)) {
  console.log('Using system-prompt.md from local file');
  prompt = fs.readFileSync(localPromptPath, 'utf-8');
} else {
  console.error('Error: No system prompt found!');
  console.error('Either set SYSTEM_PROMPT env var or create system-prompt.md');
  process.exit(1);
}

// Escape backticks and ${} for template literal
const escaped = prompt
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${');

const output = `// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/inject-prompt.js at build time

export const SYSTEM_PROMPT = \`${escaped}\`;
`;

fs.writeFileSync(outputPath, output);
console.log('Generated src/system-prompt.ts');
