/**
 * Vitest globalSetup. Ensures gitignored generated files that test
 * imports touch (e.g. src/data/site-config.ts) exist on disk so
 * vite-node can resolve the import path. The actual values are mocked
 * per-test via vi.mock — this stub is just a target for module
 * resolution.
 */

import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');

function stubIfMissing(relPath: string, content: string): void {
  const full = resolve(repoRoot, relPath);
  if (!existsSync(full)) {
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, content, 'utf-8');
  }
}

export default function setup(): void {
  // Stub for src/data/site-config.ts (consumed by src/terminal/github.ts).
  // On a fresh CI checkout the real file is generated by the build step;
  // during tests we don't need its values, just a resolvable module.
  stubIfMissing(
    'src/data/site-config.ts',
    [
      '// Auto-generated stub for tests. The real file is produced by',
      '// scripts/generate-site-config.js at build time.',
      'export const SITE_CONFIG = {',
      '  author: "", email: "", github: "", linkedin: "",',
      '  domain: "", portfolio: "",',
      '  repository: "", content_repo: "", github_owner: "",',
      '  content_posts_path: "", content_drafts_path: "",',
      '} as const;',
      'export type SiteConfig = typeof SITE_CONFIG;',
      '',
    ].join('\n')
  );

  // Stub for worker/src/system-prompt.ts (consumed by worker/src/index.ts).
  // Generated at deploy time by worker/scripts/inject-prompt.js; absent on
  // a fresh checkout. The worker test mocks request/response behavior, so
  // the actual prompt text is irrelevant.
  stubIfMissing(
    'worker/src/system-prompt.ts',
    'export const SYSTEM_PROMPT = "";\n'
  );
}
