# Ellyseum Blog - Makefile
# Common commands for Jekyll development

# Environment setup
export GEM_HOME := $(HOME)/.gems
export PATH := $(HOME)/.gems/bin:$(PATH)

.PHONY: install serve build clean deploy new-post help content prod \
        embeddings sync-prompt sync-chunks sync-all rebuild draft \
        serve-drafts doctor

# Default target
help:
	@echo "Available commands:"
	@echo "  make prod       - Full build (Vite + Jekyll) for local testing"
	@echo "  make content    - Process content from content/ directory"
	@echo "  make install    - Install Ruby dependencies"
	@echo "  make serve      - Start Jekyll server (requires prior build)"
	@echo "  make build      - Build Jekyll only (use 'make prod' for full build)"
	@echo "  make clean      - Remove generated files"
	@echo "  make deploy     - Push changes to GitHub"
	@echo "  make sync-prompt - Sync system-prompt.md to GitHub secret"
	@echo "  make sync-chunks - Sync context-chunks.json to GitHub secret"
	@echo "  make sync-all    - Sync all secrets to GitHub"
	@echo "  make rebuild    - Trigger GitHub Actions rebuild without pushing"
	@echo "  make embeddings - Regenerate embeddings from context-chunks.ts"
	@echo "  make new-post   - Create a new blog post (usage: make new-post TITLE='My Post')"

# Process content from content/ directory
content:
	@echo "Processing content..."
	bash scripts/fetch-content.sh

# Install dependencies
install:
	bundle install

# Start development server with live reload.
# Depends on `content` so _config.yml/CNAME/about exist, and runs the
# Vite build so the asset manifest the layouts reference is in place.
# Without this step, _layouts/default.html resolves to broken URLs.
serve: content
	npm run build
	bundle exec jekyll serve --livereload

# Build for production
build:
	JEKYLL_ENV=production bundle exec jekyll build

# Production build (vite + hash update + jekyll)
prod: content
	@echo "Building JS..."
	npm run build
	@echo "Building Jekyll..."
	JEKYLL_ENV=production bundle exec jekyll build
	@echo "Done! Run: npx serve _site -l 4000"

# Clean generated files. Mirrors `npm run clean` — removes only build
# outputs (never user-source posts, drafts, or _data/site.yml).
clean:
	bundle exec jekyll clean
	npm run clean

# Deploy to GitHub Pages
deploy:
	git add .
	@read -p "Commit message: " msg; \
	git commit -m "$$msg"
	git push origin main

# Create a new post
# Usage: make new-post TITLE="My New Post"
# Writes to content/ (the canonical source). _posts/ is regenerated by
# fetch-content.sh and is gitignored — writing there loses the post.
new-post:
ifndef TITLE
	$(error TITLE is required. Usage: make new-post TITLE="My Post Title")
endif
	@mkdir -p content
	@title=$$(printf '%s' "$(TITLE)"); \
	filename="content/$$(date +%Y-%m-%d)-$$(printf '%s' "$$title" | tr '[:upper:]' '[:lower:]' | tr ' ' '-').md"; \
	if [ -e "$$filename" ]; then \
	  echo "Error: $$filename already exists. Pick a different title or delete the existing file."; \
	  exit 1; \
	fi; \
	echo "---" > $$filename; \
	echo "layout: post" >> $$filename; \
	echo "title: \"$(TITLE)\"" >> $$filename; \
	echo "date: $$(date +%Y-%m-%d)" >> $$filename; \
	echo "author: " >> $$filename; \
	echo "tags: []" >> $$filename; \
	echo "---" >> $$filename; \
	echo "" >> $$filename; \
	echo "Write your post content here..." >> $$filename; \
	echo "Created: $$filename"

# Draft a new post (won't be published)
draft:
ifndef TITLE
	$(error TITLE is required. Usage: make draft TITLE="My Draft Title")
endif
	@mkdir -p content/drafts
	@title=$$(printf '%s' "$(TITLE)"); \
	filename="content/drafts/$$(printf '%s' "$$title" | tr '[:upper:]' '[:lower:]' | tr ' ' '-').md"; \
	echo "---" > $$filename; \
	echo "layout: post" >> $$filename; \
	echo "title: \"$(TITLE)\"" >> $$filename; \
	echo "author: " >> $$filename; \
	echo "tags: []" >> $$filename; \
	echo "---" >> $$filename; \
	echo "" >> $$filename; \
	echo "Write your draft content here..." >> $$filename; \
	echo "Created draft: $$filename"

# Serve with drafts visible
serve-drafts:
	bundle exec jekyll serve --livereload --drafts

# Check for broken links and issues
doctor:
	bundle exec jekyll doctor

# Sync system prompt to GitHub secret. Prefer content/system-prompt.md
# (split-repo layout) and fall back to the repo root.
sync-prompt:
	@if [ -f content/system-prompt.md ]; then src=content/system-prompt.md; \
	elif [ -f system-prompt.md ]; then src=system-prompt.md; \
	else echo "No system-prompt.md found in content/ or repo root"; exit 1; fi; \
	echo "Syncing $$src to SYSTEM_PROMPT..."; \
	gh secret set SYSTEM_PROMPT < "$$src"; \
	echo "System prompt synced to GitHub!"

# Sync context chunks to GitHub secret. Prefer content/context-chunks.json,
# fall back to the repo root.
sync-chunks:
	@if [ -f content/context-chunks.json ]; then src=content/context-chunks.json; \
	elif [ -f context-chunks.json ]; then src=context-chunks.json; \
	else echo "No context-chunks.json found in content/ or repo root"; exit 1; fi; \
	echo "Syncing $$src to CONTEXT_CHUNKS..."; \
	gh secret set CONTEXT_CHUNKS < "$$src"; \
	echo "Context chunks synced to GitHub!"

# Sync all secrets
sync-all: sync-prompt sync-chunks
	@echo "All secrets synced!"

# Trigger GitHub Actions rebuild without pushing
rebuild:
	gh workflow run "Build and Deploy" --ref main

# Regenerate embeddings from context-chunks.ts
# Requires: conda activate embeddings && pip install sentence-transformers
embeddings:
	python scripts/generate-embeddings.py
