#!/usr/bin/env node
/**
 * Injects system prompt and chat greetings into jocelyn-context.ts at build time
 * Reads from: system-prompt.md (local) or SYSTEM_PROMPT env var (CI)
 *             _data/site.yml or content/site.yml for chat greetings
 * Writes to: src/data/jocelyn-context.ts
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { parse } from 'yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.join(__dirname, '../src/data');
const outputPath = path.join(dataDir, 'jocelyn-context.ts');

// system-prompt.md lookup paths, in priority order. Local-first, then
// the content/ folder (split-repo layout where the prompt lives in the
// content repo cloned into content/).
const promptPaths = [
  path.join(__dirname, '../system-prompt.md'),
  path.join(__dirname, '../content/system-prompt.md')
];

// Site YAML paths to check
const siteYamlPaths = [
  path.join(__dirname, '../_data/site.yml'),
  path.join(__dirname, '../content/site.yml')
];

// Ensure output directory exists
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

let prompt = '';
let haveSource = false;

// Resolution order: env var (CI) → root system-prompt.md → content/system-prompt.md
if (process.env.SYSTEM_PROMPT) {
  console.log('Using SYSTEM_PROMPT from environment');
  prompt = process.env.SYSTEM_PROMPT;
  haveSource = true;
} else {
  for (const p of promptPaths) {
    if (fs.existsSync(p)) {
      console.log(`Using system prompt from ${path.relative(path.join(__dirname, '..'), p)}`);
      prompt = fs.readFileSync(p, 'utf-8');
      haveSource = true;
      break;
    }
  }
  if (!haveSource) {
    console.warn('No system prompt found — emitting empty stub.');
    console.warn('Set SYSTEM_PROMPT env var or create system-prompt.md (root or content/) to customize.');
  }
}

// Base64 encode and chunk for obfuscation. When no prompt is configured,
// we emit a plain empty-string export instead of running the obfuscator
// over an empty buffer (which would emit `_decode()` with no args).
let chunkFunctions = '';
let assembly = '""';
if (haveSource && prompt.length > 0) {
  const encoded = Buffer.from(prompt).toString('base64');
  const chunkSize = 8; // Small chunks = more annoying
  const chunks = [];
  for (let i = 0; i < encoded.length; i += chunkSize) {
    chunks.push(encoded.slice(i, i + chunkSize));
  }

  // Generate randomized function names
  const fnNames = chunks.map((_, i) => `_${Math.random().toString(36).slice(2, 8)}`);

  // Shuffle the order for extra annoyance (but track original indices)
  const indices = chunks.map((_, i) => i);
  for (let i = indices.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [indices[i], indices[j]] = [indices[j], indices[i]];
  }

  // Build the chunked functions in shuffled order
  chunkFunctions = indices.map(i =>
    `const ${fnNames[i]}=()=>"${chunks[i]}";`
  ).join('\n');

  // Build the assembly in correct order
  assembly = fnNames.map(fn => `${fn}()`).join('+');
}

// Load chat greetings from site.yml if available
let greetingLocal = `Hey! I'm the local AI assistant. I run 100% in your browser via WebGPU - no data leaves your device, nothing is sent to any server. Pretty cool, right?

Fair warning: I'm a small model, so I might get things wrong. Ask me about the blog or tech stuff. What's on your mind?`;

let greetingCloud = `Hey! I'm the AI assistant, powered by Llama 3.3 70B. Your messages go through a proxy to keep things fast and reliable.

Ask me about the blog or tech stuff. What's on your mind?`;

// Try to load greetings from site.yml
for (const yamlPath of siteYamlPaths) {
  if (fs.existsSync(yamlPath)) {
    try {
      const yamlContent = fs.readFileSync(yamlPath, 'utf-8');
      const config = parse(yamlContent);
      if (config.chat?.greeting_local) {
        greetingLocal = config.chat.greeting_local.trim();
        console.log(`Loaded greeting_local from ${yamlPath}`);
      }
      if (config.chat?.greeting_cloud) {
        greetingCloud = config.chat.greeting_cloud.trim();
        console.log(`Loaded greeting_cloud from ${yamlPath}`);
      }
      break; // Use first found
    } catch (e) {
      console.warn(`Warning: Could not parse ${yamlPath}: ${e.message}`);
    }
  }
}

// Escape backticks and ${} in greetings for template literal safety
const escapeTemplateLiteral = (s) => s.replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const output = `// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/inject-context.js at build time

${chunkFunctions}
const _decode=(s:string)=>decodeURIComponent(atob(s).split('').map(c=>'%'+('00'+c.charCodeAt(0).toString(16)).slice(-2)).join(''));
export const SYSTEM_PROMPT=_decode(${assembly});

export const GREETING_MESSAGE_LOCAL = \`${escapeTemplateLiteral(greetingLocal)}\`;

export const GREETING_MESSAGE_CLOUD = \`${escapeTemplateLiteral(greetingCloud)}\`;

// Default export for backwards compatibility
export const GREETING_MESSAGE = GREETING_MESSAGE_LOCAL;
`;

fs.writeFileSync(outputPath, output);
console.log('Generated src/data/jocelyn-context.ts');
