#!/usr/bin/env node
/**
 * Injects context chunks at build time
 * Reads from: context-chunks.json (local) or CONTEXT_CHUNKS env var (CI)
 * Writes to: src/data/context-chunks.ts
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.join(__dirname, '../src/data');
const outputPath = path.join(dataDir, 'context-chunks.ts');

// context-chunks.json lookup paths, in priority order. content/ wins
// over the repo root so split-repo users authoring in their content
// repo aren't shadowed by a stale root copy. The CONTEXT_CHUNKS env
// var still overrides both (handled below).
const chunkPaths = [
  path.join(__dirname, '../content/context-chunks.json'),
  path.join(__dirname, '../context-chunks.json')
];

// Ensure output directory exists
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

let chunksData;

// Resolution order: env var (CI) → content/context-chunks.json → root context-chunks.json
if (process.env.CONTEXT_CHUNKS) {
  console.log('Using CONTEXT_CHUNKS from environment');
  chunksData = JSON.parse(process.env.CONTEXT_CHUNKS);
} else {
  let loaded = false;
  for (const p of chunkPaths) {
    if (fs.existsSync(p)) {
      console.log(`Using chunks from ${path.relative(path.join(__dirname, '..'), p)}`);
      chunksData = JSON.parse(fs.readFileSync(p, 'utf-8'));
      loaded = true;
      break;
    }
  }
  if (!loaded) {
    console.warn('No context chunks found — emitting empty stub.');
    console.warn('Set CONTEXT_CHUNKS env var or create context-chunks.json (root or content/) to enable RAG.');
    chunksData = { chunks: [], categories: [] };
  }
}

// Build the TypeScript file
const output = `// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/inject-chunks.js at build time

export interface ContextChunk {
  id: string;
  category: string;
  content: string;
  keywords: string[];
}

export const CONTEXT_CHUNKS: ContextChunk[] = ${JSON.stringify(chunksData.chunks, null, 2)};

export const CATEGORIES = ${JSON.stringify(chunksData.categories, null, 2)} as const;
`;

fs.writeFileSync(outputPath, output);
console.log('Generated src/data/context-chunks.ts');
