#!/usr/bin/env node
/**
 * Injects system prompt into jocelyn-context.ts at build time
 * Reads from: system-prompt.md (local) or SYSTEM_PROMPT env var (CI)
 * Writes to: src/data/jocelyn-context.ts
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.join(__dirname, '../src/data');
const outputPath = path.join(dataDir, 'jocelyn-context.ts');
const localPromptPath = path.join(__dirname, '../system-prompt.md');

// Ensure output directory exists
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

let prompt;

// Try environment variable first (CI), then local file
if (process.env.SYSTEM_PROMPT) {
  console.log('Using SYSTEM_PROMPT from environment');
  prompt = process.env.SYSTEM_PROMPT;
} else if (fs.existsSync(localPromptPath)) {
  console.log('Using system-prompt.md from local file');
  prompt = fs.readFileSync(localPromptPath, 'utf-8');
} else {
  console.error('Error: No system prompt found!');
  console.error('Either set SYSTEM_PROMPT env var or create system-prompt.md');
  process.exit(1);
}

// Base64 encode and chunk for obfuscation
const encoded = Buffer.from(prompt).toString('base64');
const chunkSize = 8; // Small chunks = more annoying
const chunks = [];
for (let i = 0; i < encoded.length; i += chunkSize) {
  chunks.push(encoded.slice(i, i + chunkSize));
}

// Generate randomized function names
const fnNames = chunks.map((_, i) => `_${Math.random().toString(36).slice(2, 8)}`);

// Shuffle the order for extra annoyance (but track original indices)
const indices = chunks.map((_, i) => i);
for (let i = indices.length - 1; i > 0; i--) {
  const j = Math.floor(Math.random() * (i + 1));
  [indices[i], indices[j]] = [indices[j], indices[i]];
}

// Build the chunked functions in shuffled order
const chunkFunctions = indices.map(i =>
  `const ${fnNames[i]}=()=>"${chunks[i]}";`
).join('\n');

// Build the assembly in correct order
const assembly = fnNames.map(fn => `${fn}()`).join('+');

const output = `// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/inject-context.js at build time

${chunkFunctions}
const _decode=(s:string)=>decodeURIComponent(atob(s).split('').map(c=>'%'+('00'+c.charCodeAt(0).toString(16)).slice(-2)).join(''));
export const JOCELYN_SYSTEM_PROMPT=_decode(${assembly});

export const GREETING_MESSAGE_LOCAL = \`Hey! I'm Jocelyn's local AI assistant. I run 100% in your browser via WebGPU - no data leaves your device, nothing is sent to any server. Pretty cool, right?

Fair warning: I'm a small model, so I might get things wrong. Ask me about the blog, my projects, or tech stuff. What's on your mind?\`;

export const GREETING_MESSAGE_CLOUD = \`Hey! I'm Jocelyn's AI assistant, powered by Llama 3.3 70B. Your messages go through a proxy to keep things fast and reliable.

Ask me about the blog, my projects, work history, or tech stuff. What's on your mind?\`;

// Default export for backwards compatibility
export const GREETING_MESSAGE = GREETING_MESSAGE_LOCAL;
`;

fs.writeFileSync(outputPath, output);
console.log('Generated src/data/jocelyn-context.ts');
