#!/usr/bin/env node
/**
 * Injects context chunks at build time
 * Reads from: context-chunks.json (local) or CONTEXT_CHUNKS env var (CI)
 * Writes to: src/data/context-chunks.ts
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.join(__dirname, '../src/data');
const outputPath = path.join(dataDir, 'context-chunks.ts');
const localChunksPath = path.join(__dirname, '../context-chunks.json');

// Ensure output directory exists
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

let chunksData;

// Try environment variable first (CI), then local file
if (process.env.CONTEXT_CHUNKS) {
  console.log('Using CONTEXT_CHUNKS from environment');
  chunksData = JSON.parse(process.env.CONTEXT_CHUNKS);
} else if (fs.existsSync(localChunksPath)) {
  console.log('Using context-chunks.json from local file');
  chunksData = JSON.parse(fs.readFileSync(localChunksPath, 'utf-8'));
} else {
  console.error('Error: No context chunks found!');
  console.error('Either set CONTEXT_CHUNKS env var or create context-chunks.json');
  process.exit(1);
}

// Build the TypeScript file
const output = `// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/inject-chunks.js at build time

export interface ContextChunk {
  id: string;
  category: string;
  content: string;
  keywords: string[];
}

export const CONTEXT_CHUNKS: ContextChunk[] = ${JSON.stringify(chunksData.chunks, null, 2)};

export const CATEGORIES = ${JSON.stringify(chunksData.categories, null, 2)} as const;
`;

fs.writeFileSync(outputPath, output);
console.log('Generated src/data/context-chunks.ts');
